title: Bose of All Things
author: Ankit Bose
email: bse.nkt24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is created as part of learning GitHub Pages.

# social links
twitter_username: ionbasket # DO NOT include the @ character, or else the build will fail!
github_username:  AnkitBose # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
